// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plog.proto

package plogproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CtxType int32

const (
	CtxType_log   CtxType = 0
	CtxType_state CtxType = 1
	CtxType_count CtxType = 2
	CtxType_dict  CtxType = 3
	CtxType_list  CtxType = 4
)

var CtxType_name = map[int32]string{
	0: "log",
	1: "state",
	2: "count",
	3: "dict",
	4: "list",
}
var CtxType_value = map[string]int32{
	"log":   0,
	"state": 1,
	"count": 2,
	"dict":  3,
	"list":  4,
}

func (x CtxType) Enum() *CtxType {
	p := new(CtxType)
	*p = x
	return p
}
func (x CtxType) String() string {
	return proto.EnumName(CtxType_name, int32(x))
}
func (x *CtxType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CtxType_value, data, "CtxType")
	if err != nil {
		return err
	}
	*x = CtxType(value)
	return nil
}
func (CtxType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_plog_43ef7991fd849bf8, []int{0}
}

type Plog struct {
	CtxId *uint64 `protobuf:"varint,1,opt,name=ctx_id,json=ctxId" json:"ctx_id,omitempty"`
	// All these are optional, more than one can be set.
	// E.g. all three can be used together to send a whole context in a single message.
	Open                 *OpenContext   `protobuf:"bytes,2,opt,name=open" json:"open,omitempty"`
	Msg                  []*PlogMessage `protobuf:"bytes,3,rep,name=msg" json:"msg,omitempty"`
	Close                *bool          `protobuf:"varint,4,opt,name=close" json:"close,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Plog) Reset()         { *m = Plog{} }
func (m *Plog) String() string { return proto.CompactTextString(m) }
func (*Plog) ProtoMessage()    {}
func (*Plog) Descriptor() ([]byte, []int) {
	return fileDescriptor_plog_43ef7991fd849bf8, []int{0}
}
func (m *Plog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plog.Unmarshal(m, b)
}
func (m *Plog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plog.Marshal(b, m, deterministic)
}
func (dst *Plog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plog.Merge(dst, src)
}
func (m *Plog) XXX_Size() int {
	return xxx_messageInfo_Plog.Size(m)
}
func (m *Plog) XXX_DiscardUnknown() {
	xxx_messageInfo_Plog.DiscardUnknown(m)
}

var xxx_messageInfo_Plog proto.InternalMessageInfo

func (m *Plog) GetCtxId() uint64 {
	if m != nil && m.CtxId != nil {
		return *m.CtxId
	}
	return 0
}

func (m *Plog) GetOpen() *OpenContext {
	if m != nil {
		return m.Open
	}
	return nil
}

func (m *Plog) GetMsg() []*PlogMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Plog) GetClose() bool {
	if m != nil && m.Close != nil {
		return *m.Close
	}
	return false
}

type OpenContext struct {
	Ctxtype              *CtxType `protobuf:"varint,1,opt,name=ctxtype,enum=plogproto.CtxType" json:"ctxtype,omitempty"`
	Key                  []string `protobuf:"bytes,2,rep,name=key" json:"key,omitempty"`
	ParentCtxId          *uint64  `protobuf:"varint,3,opt,name=parent_ctx_id,json=parentCtxId" json:"parent_ctx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenContext) Reset()         { *m = OpenContext{} }
func (m *OpenContext) String() string { return proto.CompactTextString(m) }
func (*OpenContext) ProtoMessage()    {}
func (*OpenContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_plog_43ef7991fd849bf8, []int{1}
}
func (m *OpenContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenContext.Unmarshal(m, b)
}
func (m *OpenContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenContext.Marshal(b, m, deterministic)
}
func (dst *OpenContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenContext.Merge(dst, src)
}
func (m *OpenContext) XXX_Size() int {
	return xxx_messageInfo_OpenContext.Size(m)
}
func (m *OpenContext) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenContext.DiscardUnknown(m)
}

var xxx_messageInfo_OpenContext proto.InternalMessageInfo

func (m *OpenContext) GetCtxtype() CtxType {
	if m != nil && m.Ctxtype != nil {
		return *m.Ctxtype
	}
	return CtxType_log
}

func (m *OpenContext) GetKey() []string {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *OpenContext) GetParentCtxId() uint64 {
	if m != nil && m.ParentCtxId != nil {
		return *m.ParentCtxId
	}
	return 0
}

type PlogMessage struct {
	Key                  *string  `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlogMessage) Reset()         { *m = PlogMessage{} }
func (m *PlogMessage) String() string { return proto.CompactTextString(m) }
func (*PlogMessage) ProtoMessage()    {}
func (*PlogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_plog_43ef7991fd849bf8, []int{2}
}
func (m *PlogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlogMessage.Unmarshal(m, b)
}
func (m *PlogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlogMessage.Marshal(b, m, deterministic)
}
func (dst *PlogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlogMessage.Merge(dst, src)
}
func (m *PlogMessage) XXX_Size() int {
	return xxx_messageInfo_PlogMessage.Size(m)
}
func (m *PlogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PlogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PlogMessage proto.InternalMessageInfo

func (m *PlogMessage) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *PlogMessage) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Plog)(nil), "plogproto.plog")
	proto.RegisterType((*OpenContext)(nil), "plogproto.open_context")
	proto.RegisterType((*PlogMessage)(nil), "plogproto.plog_message")
	proto.RegisterEnum("plogproto.CtxType", CtxType_name, CtxType_value)
}

func init() { proto.RegisterFile("plog.proto", fileDescriptor_plog_43ef7991fd849bf8) }

var fileDescriptor_plog_43ef7991fd849bf8 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xbf, 0x6e, 0xb3, 0x30,
	0x14, 0xc5, 0x3f, 0xc7, 0xe6, 0x4b, 0x72, 0x93, 0x56, 0xd6, 0x55, 0xaa, 0x32, 0x22, 0x26, 0xfa,
	0x47, 0x19, 0x32, 0x74, 0xea, 0x96, 0xa9, 0xab, 0xd5, 0x1d, 0x21, 0x63, 0x21, 0x54, 0x82, 0x2d,
	0x7c, 0x53, 0xc1, 0x33, 0xf4, 0xa5, 0x2b, 0x43, 0xd2, 0xa2, 0x6e, 0xbf, 0x73, 0x75, 0xee, 0xd1,
	0x39, 0x00, 0xae, 0xb1, 0xd5, 0xde, 0x75, 0x96, 0x2c, 0xae, 0x03, 0x8f, 0x98, 0x7e, 0x31, 0x10,
	0x41, 0xe1, 0x1d, 0xfc, 0xd7, 0xd4, 0xe7, 0x75, 0x19, 0xb3, 0x84, 0x65, 0x42, 0x45, 0x9a, 0xfa,
	0xb7, 0x12, 0x9f, 0x40, 0x58, 0x67, 0xda, 0x78, 0x91, 0xb0, 0x6c, 0x73, 0xb8, 0xdf, 0xff, 0x7c,
	0xee, 0xc3, 0x39, 0xd7, 0xb6, 0x25, 0xd3, 0x93, 0x1a, 0x4d, 0xf8, 0x00, 0xfc, 0xe4, 0xab, 0x98,
	0x27, 0xfc, 0x8f, 0x37, 0x50, 0x7e, 0x32, 0xde, 0x17, 0x95, 0x51, 0xc1, 0x83, 0x3b, 0x88, 0x74,
	0x63, 0xbd, 0x89, 0x45, 0xc2, 0xb2, 0x95, 0x9a, 0x44, 0xda, 0xc1, 0x76, 0x1e, 0x8b, 0xcf, 0xb0,
	0xd4, 0xd4, 0xd3, 0xe0, 0xcc, 0xd8, 0xea, 0xf6, 0x80, 0xb3, 0xd0, 0x23, 0xf5, 0xef, 0x83, 0x33,
	0xea, 0x6a, 0x41, 0x09, 0xfc, 0xc3, 0x0c, 0xf1, 0x22, 0xe1, 0xd9, 0x5a, 0x05, 0xc4, 0x14, 0x6e,
	0x5c, 0xd1, 0x99, 0x96, 0xf2, 0xcb, 0x36, 0x3e, 0x6e, 0xdb, 0x4c, 0xc7, 0x63, 0x58, 0x98, 0xbe,
	0xc0, 0x76, 0x5e, 0xef, 0x37, 0x85, 0x5d, 0x53, 0x76, 0x10, 0x7d, 0x16, 0xcd, 0xd9, 0x8c, 0xdf,
	0x5b, 0x35, 0x89, 0xc7, 0x57, 0x58, 0x5e, 0x1a, 0xe0, 0x12, 0x78, 0x63, 0x2b, 0xf9, 0x0f, 0xd7,
	0x10, 0x79, 0x2a, 0xc8, 0x48, 0x16, 0x50, 0xdb, 0x73, 0x4b, 0x72, 0x81, 0x2b, 0x10, 0x65, 0xad,
	0x49, 0xf2, 0x40, 0x4d, 0xed, 0x49, 0x8a, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x78, 0x67,
	0x77, 0x8f, 0x01, 0x00, 0x00,
}
